### ISSUE TITLE
How to use it? I need a instraction(

### ISSUE THREAD

**Issue by frogbodbod** [gsrunion/LaserBoxGrblBridge#1]
Hello, i have a laserbox, and i want to use with them LaserGRBL or LightBURN. How to do it. Often i use USB to connect my Laserbox

**Comment by gsrunion** [comment]
Not really working at the moment. I was in a bit of a reverse engineering phase when my last eat child was bit and have not gotten back to this.

**Comment by gsrunion** [comment]
Check out https://github.com/fritzw/xtm1_toolkit he seems to be further along than me but he is targeting the x1 cutter. There are plenty of similarities but also some differences (reversed coordinates) that you would have to account for.

**Comment by frogbodbod** [comment]
Thank you!
